using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
 * 问题描述：
 * Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling(洗牌) string s and then
    add one more letter at a random position.

    Find the letter that was added in t.
 * 
*/

namespace FindTheDifference
{
    class Program
    {
        static void Main(string[] args)
        {
            string s = "asdfg";
            string t = "dsagfk";
            solution sol = new solution();
            char c = sol.FindTheDifference(s, t);
            Console.WriteLine("{0} is the latter that the added.", c);
            Console.Read();
        }
    }

    public class solution
    {
        public char FindTheDifference(string s, string t)
        {
            int res = 0;
            int i = 0;
            for (i = 0; i < s.Length; i++)
            {
                res ^= (s[i] ^ t[i]);
            }

            return (char)(res ^ t[i]);
        }
    }
}
